services:
  angular-app:
    build:
      context: .
      dockerfile: docker-app/Dockerfile
    container_name: angular-app
    ports:
      - '4200:4200'
    volumes:
      - ./:/usr/src/app
    environment:
      - STYLE=scss
